name: slide_transition_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^2.0.4
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  http: ^0.13.3
  shared_preferences: ^2.0.7
  #cloud_firestore:
  provider:
  retrofit: ^2.0.1
  dio: ^4.0.0
  json_annotation: ^4.1.0
  built_value: ^8.1.2
  custom_radio_grouped_button: any

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^5.0.0
  retrofit_generator: ^2.0.1+1
  flutter_launcher_icons: ^0.9.2

dependency_overrides:
  meta: ^1.7.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the images in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/happy_emoji.png
     - assets/images/happy.png
     - assets/images/cool.png
     - assets/images/cool1.png
     - assets/images/wink.png
     - assets/images/surprised.png
     - assets/images/backgroun_image.png
     - assets/images/smile-removebg-preview.png
     - assets/images/smile2-removebg-preview.png
     - assets/images/smile3-removebg-preview.png
     - assets/images/smile4-removebg-preview.png
     - assets/images/smile5-removebg-preview.png
     - assets/images/smile6-removebg-preview.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
